# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 08:11
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portfolio', '0003_auto_20170511_0609'),
        ('Clients', '0004_auto_20170509_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('net_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='net amount')),
                ('mode_of_payment', models.CharField(max_length=5, verbose_name='mode of payment')),
                ('vat', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='vat')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreement', to='Clients.Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_agreement', to='Portfolio.Product')),
            ],
            options={
                'db_table': 'contract_agreement',
            },
        ),
        migrations.CreateModel(
            name='ContractAgreementPurposes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='amount')),
                ('installment', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='installment')),
                ('contract_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='Invoicing.ContractAgreement')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Purpose')),
            ],
        ),
    ]
