# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_auto_20170509_1120'),
        ('Invoicing', '0002_auto_20170514_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAgreementConcernPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(max_length=3)),
                ('concern_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Clients.ConcernPerson')),
                ('contract_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concern_persons', to='Invoicing.ContractAgreement')),
            ],
            options={
                'db_table': 'contract_agreement_concern_persons',
            },
        ),
    ]
