# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0003_contractagreementconcernperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreement',
            name='end_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
    ]
