# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0004_contractagreement_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractagreementconcernperson',
            old_name='communication_type',
            new_name='concern_person_type',
        ),
    ]
