# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 11:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0006_auto_20170516_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreementpurpose',
            name='amount_per_installment',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='amount per installment'),
        ),
    ]
