# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 08:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0008_auto_20170518_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.TextField()),
                ('date', models.DateField()),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)])),
                ('contract_agreement_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Invoicing.ContractAgreementPurpose')),
            ],
            options={
                'db_table': 'bill_schedule',
            },
        ),
    ]
