# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0009_billschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billschedule',
            old_name='date',
            new_name='schedule_date',
        ),
    ]
