# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0010_auto_20170523_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillInstallmentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_type', models.IntegerField()),
                ('particular', models.TextField()),
                ('schedule_start_date', models.DateField()),
                ('contract_agreement_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoicing.ContractAgreementPurpose')),
            ],
            options={
                'db_table': 'bill_installment_config',
            },
        ),
    ]
