# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0011_billinstallmentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='billinstallmentconfig',
            name='use_sequence',
            field=models.BooleanField(default=False),
        ),
    ]
