# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0012_billinstallmentconfig_use_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractagreement',
            old_name='start_date',
            new_name='agreement_date',
        ),
    ]
