# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_auto_20170530_0535'),
        ('Invoicing', '0014_auto_20170530_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractagreement',
            name='invoice_template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Settings.Invoicetemplate'),
            preserve_default=False,
        ),
    ]
