# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0015_contractagreement_invoice_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='billschedule',
            name='installment_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
