# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 10:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0016_billschedule_installment_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('contract_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='Invoicing.ContractAgreement')),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.AlterModelTable(
            name='billinstallmentconfig',
            table='bill_installment_configs',
        ),
        migrations.AlterModelTable(
            name='billschedule',
            table='bill_schedules',
        ),
        migrations.AddField(
            model_name='billschedule',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_schedules', to='Invoicing.Invoice'),
        ),
    ]
