# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0019_auto_20170606_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
