# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0020_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
