# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0022_invoice_invoice_sequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinstallmentconfig',
            name='contract_agreement_purpose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Invoicing.ContractAgreementPurpose'),
        ),
    ]
