# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-07 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0026_auto_20170607_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='billschedule',
            name='bill_installment_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_schedules', to='Invoicing.BillInstallmentConfig'),
        ),
    ]
