# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoicing', '0027_billschedule_bill_installment_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
