# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 15:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('description', models.TextField(default='It is a description field', verbose_name='description')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('concern_persons', models.ManyToManyField(to='Employees.Employee')),
            ],
            options={
                'db_table': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('product_code', models.CharField(max_length=20, unique=True, verbose_name='code')),
                ('description', models.TextField(default='It is a description field', verbose_name='description')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(null=True, verbose_name='end date')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductConcernPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Employee')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Product')),
            ],
            options={
                'db_table': 'product_concern_persons',
            },
        ),
        migrations.CreateModel(
            name='ProductPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, verbose_name='amount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Product')),
            ],
            options={
                'db_table': 'product_purposes',
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('description', models.TextField(default='It is a description field', verbose_name='description')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'purposes',
            },
        ),
        migrations.AddField(
            model_name='productpurpose',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Purpose'),
        ),
        migrations.AddField(
            model_name='product',
            name='concern_persons',
            field=models.ManyToManyField(through='Portfolio.ProductConcernPerson', to='Employees.Employee'),
        ),
        migrations.AddField(
            model_name='product',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Portfolio.Portfolio'),
        ),
        migrations.AddField(
            model_name='product',
            name='purposes',
            field=models.ManyToManyField(through='Portfolio.ProductPurpose', to='Portfolio.Purpose'),
        ),
    ]
