# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-11 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurpose',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='amount'),
        ),
    ]
