# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20170511_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_code',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('Project', 'Project'), ('Product', 'Product')], default=1, max_length=7, verbose_name='product type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Portfolio.Portfolio'),
        ),
    ]
