# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20170606_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(default='S', max_length=5),
        ),
    ]
