# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0009_auto_20170606_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
