# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 15:49
from __future__ import unicode_literals

import Employees.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='title')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='employee id')),
                ('father_name', models.CharField(max_length=40, verbose_name='father name')),
                ('mother_name', models.CharField(max_length=40, verbose_name='mother name')),
                ('present_address', models.CharField(max_length=100, verbose_name='present address')),
                ('permanent_address', models.CharField(max_length=100, verbose_name='permanent address')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=6, verbose_name='gender')),
                ('date_of_birth', models.DateField(verbose_name='date of birth')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_of_joining', models.DateField(verbose_name='date of joining')),
                ('starting_salary', models.FloatField(null=True, verbose_name='starting salary')),
                ('current_salary', models.FloatField(null=True, verbose_name='current salary')),
                ('national_id', models.CharField(max_length=20, null=True, verbose_name='national id')),
                ('profile_image', models.ImageField(null=True, upload_to=Employees.models.upload_location, verbose_name='profile picture')),
                ('status', models.BooleanField(verbose_name='status')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employees.Designation')),
            ],
            options={
                'db_table': 'employees',
            },
        ),
    ]
