# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 04:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_auto_20170509_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_salary',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='current salary'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='starting_salary',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1.0)], verbose_name='starting salary'),
        ),
    ]
