# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Employees', '0005_auto_20170606_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='designation_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='designation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designation_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
