# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 09:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Portfolio', '0010_auto_20170606_0725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Invoicing', '0028_invoice_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('description', models.TextField(null=True)),
                ('collection_date', models.DateField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_collected_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_created_by', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='Invoicing.Invoice')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_details', to='Accounts.Collection')),
                ('contract_agreement_purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invoicing.ContractAgreementPurpose')),
            ],
            options={
                'db_table': 'collection_details',
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_id', models.CharField(max_length=20)),
                ('seq_num', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_created_by', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='Portfolio.Product')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenditures',
            },
        ),
        migrations.CreateModel(
            name='ExpenditureDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditure_details', to='Accounts.Expenditure')),
            ],
            options={
                'db_table': 'expenditure_details',
            },
        ),
        migrations.CreateModel(
            name='ExpensePurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_purpose_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_purpose_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_purposes',
            },
        ),
        migrations.AddField(
            model_name='expendituredetail',
            name='expense_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='Accounts.ExpensePurpose'),
        ),
    ]
