# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bankaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_account', models.CharField(max_length=40, verbose_name='name of account')),
                ('account_no', models.CharField(max_length=20, verbose_name='account no')),
                ('bank_name', models.CharField(max_length=40, verbose_name='bank name')),
                ('branch_name', models.CharField(max_length=40, verbose_name='branch name')),
                ('address', models.CharField(max_length=100, verbose_name='address')),
                ('swift_code', models.CharField(max_length=50, verbose_name='swift code')),
                ('routing_no', models.CharField(max_length=20, verbose_name='routing no')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField()),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'account_details',
            },
        ),
    ]
