# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='account no'),
        ),
        migrations.AlterField(
            model_name='invoicetemplate',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='title'),
        ),
    ]
