# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_no',
            field=models.CharField(max_length=20, unique=True, verbose_name='account no'),
        ),
    ]
