# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0003_auto_20170530_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicetemplate',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='title'),
        ),
    ]
