# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 19:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0004_auto_20170531_0944'),
        ('Settings', '0003_auto_20170531_2140'),
    ]

    operations = [
    ]
