# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 08:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0005_merge_20170604_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.PositiveIntegerField(default=None, null=True, verbose_name='branch id')),
                ('holiday_date', models.DateField(verbose_name='holiday date')),
                ('holiday_type', models.CharField(max_length=7, verbose_name='holiday type')),
                ('description', models.TextField(null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.PositiveIntegerField()),
                ('updated_by', models.PositiveIntegerField(null=True)),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
