# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0007_auto_20170606_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bankaccount_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holiday_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holiday_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
