# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concernperson',
            name='contact_number',
            field=models.CharField(default=111, max_length=20, verbose_name='contact number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concernperson',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AlterUniqueTogether(
            name='concernperson',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='concernperson',
            name='order',
        ),
    ]
