# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0002_auto_20170509_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(verbose_name='code'),
        ),
    ]
