# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0003_auto_20170509_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
    ]
