# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-06 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0004_auto_20170509_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='designation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='division',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='concernperson',
            name='status',
            field=models.BooleanField(),
        ),
    ]
