# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-13 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clients', '0006_auto_20170606_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
