# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 08:10
from __future__ import unicode_literals

import Auth.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullname', models.CharField(max_length=50, verbose_name='fullname')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('status', models.BooleanField(default=True, verbose_name='status')),
                ('profile_image', models.ImageField(null=True, upload_to=Auth.models.upload_location, verbose_name='profile photo')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', Auth.models.UserManager()),
            ],
        ),
    ]
