# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_auto_20170606_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_token_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
